FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir streamlit==1.39.0 -r requirements.txt

COPY ui/streamlit ./ui/streamlit

ENV STREAMLIT_SERVER_PORT=8501 \
    STREAMLIT_SERVER_HEADLESS=true

EXPOSE 8501
USER 65532:65532

ENTRYPOINT ["streamlit", "run", "ui/streamlit/app.py"]
